name       : python-pyls-black
version    : 0.4.6
release    : 1
source     :
    - https://github.com/rupert/pyls-black/archive/v0.4.6.tar.gz : c591f57b28852e095dafb87cdd3d16fc3dfe188ec199b728f34569d472d63150
homepage   : https://github.com/rupert/pyls-black
license    : MIT
component  : programming.python
summary    : Black plugin for the Python Language Server
description: |
    Black plugin for the Python Language Server  
builddeps  :
    - python-black
    - python-language-server
    - python-pytest
rundeps    :
    - python-black
    - python-language-server
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
