name       : python-pyls-black
version    : 0.4.7
release    : 3
source     :
    - https://github.com/rupert/pyls-black/archive/refs/tags/v0.4.7.tar.gz : 828ae1cbd1c7eb1bcdc17fe2a480917ff91ddfef91123b5a26f8638a74e0822c
homepage   : https://github.com/rupert/pyls-black
license    : MIT
component  : programming.python
summary    : Black plugin for the Python Language Server
description: |
    Black plugin for the Python Language Server.
builddeps  :
    - python-black
    - python-language-server
    - python-pytest
rundeps    :
    - python-black
    - python-language-server
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3 -v
